<?
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true)
{
	die();
}
use Bitrix\Main\Localization\Loc;

//Loc::loadLanguageFile(__FILE__);
Loc::loadLanguageFile($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/socialnetwork/install/js/socialnetwork/commentaux/config.php');
Loc::loadLanguageFile($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/socialnetwork/lib/commentaux/createtask.php');

return array(
	'js' => '/bitrix/js/socialnetwork/commentaux/socialnetwork.commentaux.js',
	'lang_additional' => array(
		'SONET_EXT_COMMENTAUX_CREATE_TASK_PATH' => \Bitrix\Main\Config\Option::get('socialnetwork', 'user_page', SITE_DIR.'company/personal/').'user/#user_id#/tasks/task/view/#task_id#/',
		'SONET_COMMENTAUX_JS_CREATETASK_POST_BLOG_POST' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_BLOG_POST'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_TASK' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_TASK'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_FORUM_TOPIC' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_FORUM_TOPIC'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_CALENDAR_EVENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_CALENDAR_EVENT'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_TIMEMAN_ENTRY' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_TIMEMAN_ENTRY'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_TIMEMAN_REPORT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_TIMEMAN_REPORT'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_LOG_ENTRY' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_LOG_ENTRY'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_PHOTO_ALBUM' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_PHOTO_ALBUM'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_PHOTO_PHOTO' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_PHOTO_PHOTO'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_WIKI' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_WIKI'),
		'SONET_COMMENTAUX_JS_CREATETASK_POST_LISTS_NEW_ELEMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_POST_LISTS_NEW_ELEMENT'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_BLOG_COMMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_BLOG_COMMENT'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_TASK' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_TASK'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_CALENDAR' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_CALENDAR'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_FORUM_TOPIC' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_FORUM_TOPIC'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_TIMEMAN_ENTRY' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_TIMEMAN_ENTRY'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_TIMEMAN_REPORT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_TIMEMAN_REPORT'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_PHOTO_PHOTO' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_PHOTO_PHOTO'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_WIKI' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_WIKI'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_FORUM_POST_LISTS_NEW_ELEMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_FORUM_POST_LISTS_NEW_ELEMENT'),
		'SONET_COMMENTAUX_JS_CREATETASK_COMMENT_LOG_COMMENT' => Loc::getMessage('SONET_COMMENTAUX_CREATETASK_COMMENT_LOG_COMMENT'),
	),
	'rel' => array('render_parts')
);