<?
$MESS["MD_EMPLOYEES_TITLE"] = "Employees";
$MESS["MD_EMPLOYEES_ALL"] = "All employees";
$MESS["MD_GROUPS_TITLE"] = "Workgroups";
$MESS["MD_EXTRANET"] = "Extranet";
$MESS["MD_DISK_TABLE_FOLDERS_FILES"] = "Folders: #FOLDERS#  Files: #FILES#";
$MESS["MD_MOBILE_APPLICATION"] = "Mobile application";
$MESS["MD_GENERATE_BY_MOBILE"] = "Generated by application";
$MESS["MD_COMPONENT_IM_RECENT"] = "Chats";
$MESS["MD_COMPONENT_IM_OPENLINES"] = "Open Channels";
$MESS["MD_COMPONENT_MORE"] = "Menu";
?>